import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import schoolsRouter from "./schools";
import usersRouter from "./users";
import programsRouter from "./programs";
import coursesRouter from "./courses";
import assignmentsRouter from "./assignments";
import submissionsRouter from "./submissions";
import announcementsRouter from "./announcements";
import notificationsRouter from "./notifications";
import applicationsRouter from "./applications";
import attendanceRouter from "./attendance";
import dashboardRouter from "./dashboard";
import courseResourcesRouter from "./course-resources";
import schoolResourcesRouter from "./school-resources";
import chatRouter from "./chat";
import forumRouter from "./forum";
import videoRouter from "./video";
import quizzesRouter from "./quizzes";
import permissionsRouter from "./permissions";
import formBuilderRouter from "./form-builder";
import gradingRouter from "./grading";
import invitationsRouter from "./invitations";
import analyticsRouter from "./analytics";
import remindersRouter from "./reminders";
import messagesRouter from "./messages";
import superAdminRouter from "./super-admin";
import activityLogRouter from "./activityLog";
import fileConverterRouter from "./fileConverter";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(schoolsRouter);
router.use(usersRouter);
router.use(programsRouter);
router.use(coursesRouter);
router.use(assignmentsRouter);
router.use(submissionsRouter);
router.use(announcementsRouter);
router.use(notificationsRouter);
router.use(applicationsRouter);
router.use(attendanceRouter);
router.use(dashboardRouter);
router.use(courseResourcesRouter);
router.use(schoolResourcesRouter);
router.use(chatRouter);
router.use(forumRouter);
router.use(videoRouter);
router.use(quizzesRouter);
router.use(permissionsRouter);
router.use(formBuilderRouter);
router.use(gradingRouter);
router.use(invitationsRouter);
router.use(analyticsRouter);
router.use(remindersRouter);
router.use(messagesRouter);
router.use(superAdminRouter);
router.use(activityLogRouter);
router.use(fileConverterRouter);

export default router;
